package com.ft.db.mapping;
// Generated Sep 12, 2016 3:37:18 PM by Hibernate Tools 4.3.1

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

    private int id;
    private String userName;
    private String passWord;
    private String remark;

    public User() {
    }

    public User(int id) {
        this.id = id;
    }

    public User(int id, String userName, String passWord, String remark) {
        this.id = id;
        this.userName = userName;
        this.passWord = passWord;
        this.remark = remark;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getUserName() {
        return this.userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getPassWord() {
        return this.passWord;
    }

    public void setPassWord(String passWord) {
        this.passWord = passWord;
    }

    public String getRemark() {
        return this.remark;
    }

    public void setRemark(String remark) {
        this.remark = remark;
    }

}
